---
version: "2"
services:
  build:
    image: golang:1.17
    working_dir: /app
    volumes:
      - .:/app
    tmpfs:
      - /app/target:exec
    command: >
      /bin/sh -c '
      go run main.go
      '
    ports:
      - "8080:8080"
